# Generated by Django 4.0.3 on 2022-04-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_order_host_client_address_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
