# Generated by Django 4.0.3 on 2022-04-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_client_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='phone_number',
        ),
    ]
