# Generated by Django 4.0.3 on 2022-04-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_number_client_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='description',
            new_name='notes',
        ),
    ]
